// This file contains helper functions for generating random data for seeding a database.
module.exports.descriptors = [
    'Sundarbans',
    'Sacred',
    'Majestic',
    'Vibrant',
    'Mystic',
    'Tropical',
    'Himalayan',
    'Ancient',
    'Lush',
    'Golden',
    'Peaceful',
    'Serene',
    'Emerald',
    'Misty',
    'Rolling',
    'Sapphire',
    'Riverine',
    'Crimson',
    'Opal',
    'Vast'
]

module.exports.places = [
    'Hills',
    'Fort',
    'Plateau',
    'Ghat',
    'Lake',
    'Temple',
    'Tundra',
    'Valley',
    'Backwaters',
    'Desert',
    'Jungle',
    'Park',
    'Wilds',
    'Caves',
    'Coast',
    'Shoreline',
    'Mountains',
    'Safari',
    'Island',
    'Oasis',
]
